AxisCommunications/docker-acap

- Dockerfile.dockerd
- Makefile.dockerd
- build.sh
The moby developers strongly recommends not stripping the binaries, see
https://github.com/moby/moby/blob/master/project/PACKAGERS.md#stripping-binaries
for more information
> Don't strip the built docker binaries

- README.md
The client certificate is called `cert` in the official Docker documentation we link to.
> Fix TLS setup verify script

- app/dockerdwrapper.c
The exec-root have to be located on tmpfs as it needs to be wiped on reboot, see:
https://github.com/docker/for-linux/issues/809#issuecomment-769455059
It is no problem to place exec-root on the default location (/var/run/docker) as only execution state is stored there, which does not take up much space.
> Moving exec-root to tmpfs

- README.md
Consistency between this repository and the ACAP Computer Vision SDK examples repository is somewhat important, especially when it comes to variable names. I've introduced the usage of the `DOCKER_PORT` variable in this repository, easing the process of fulfilling the examples requirements, where this repository almost always is a prerequisites for running an example.
If we think that this is beneficial, I'll update the Docker Compose ACAP repository accordingly.
> Consistent Docker port variable name

- README.md
It was discovered that using an old SD card made calls to the ACAP Runtime very slow quite frequently.
> Update README.md with SD Card specifications

- build.sh
With the single build dir `build`, it doesn't work very well to build more than one architecture in the tree without cleaning it.
> build.sh: Use separate build dir for each architecture

- app/postinstallscript.sh
This will signal acapctl to stop and fail the installation process.
> Fail postinstall script with EX_NOPERM if not root

- app/preuninstallscript.sh
This will signal acapctl to stop and fail the uninstallation process.
> Fail preuninstall script with EX_NOPERM if not root

- README.md
- app/manifest.json
- app/postinstallscript.sh
- app/preuninstallscript.sh
Allows user sub-groups to be mapped to containers.
NB! If a container needs sub-group access it has to use the group-add flag. The sub-group ids will be stated in /proc/<dockerd-pid>/gid_map
> Added sub-groups for the ACAP user

- README.md
Adding a message to inform that it is required to have root allowed to install docker acap
> Add note about root requirement

- app/dockerdwrapper.c
The default path when data-root is not set creates a .local folder in /usr/local/packages/dockerdwrapper. This change sets it instead to /usr/local/packages/dockerdwrapper/localdata/data
> set path for internal storage

- app/dockerdwrapper.c
> Package settings in a struct and reduce code duplication

- app/dockerdwrapper.c
Make more parts of the code agnostic to if the data root will be on an SD card or internal flash by replacing the the "use_sdcard" Boolean with the path to the data root.
> Pass around data root in settings struct

- app/dockerdwrapper.c
Since 'error' is not passed in to setup_axparameter(), it will not be set in case setup_axparameter() fails. However, it wasn't possible to get setup_axparameter() to fail. Both ax_parameter_new() and ax_parameter_register_callback() are apparently valid to call even with a non-existing application name.
> Remove unused error variable

- app/dockerdwrapper.c
Callbacks from unknown parameters isn't something that happens, and if it did, it wouldn't be a big deal anyway.
Removing is a step towards removing global variable 'restart_dockerd'.
> Remove handling of unknown parameters in callback

- app/dockerdwrapper.c
By running g_main_loop_run() in a while-loop, other parts of the program can retry starting dockerd by simply calling g_main_loop_quit(). To exit this loop, call quit_program(), which will also set the global acap_exit_code variable.
This is needed when e.g. AXStorage is used to wait for SD card to become available.
> Centralize restart of dockerd

- README.md
- app/dockerdwrapper.c
- app/manifest.json
Adding option to toggle use of TCP socket, default set to "yes".
At least one of the sockets need to be selected for dockerd to be started.
Fixes #126
> Add a new parameter to have an option to choose TCP socket creation

- app/dockerdwrapper.c
Pass around data root in settings struct, also setting data-root to the default location if sd card is not selected.
> Pass around SD card area instead of using global constant

- .github/workflows/cd.yml
- Dockerfile
- README.md
- build.sh
The docker copy-create step is not needed if the Dockerfile itself moves wanted files
> Let docker build output eap-file

- Dockerfile
- app/dockerdwrapper.c
- Using axparameter library from ACAP native SDK.
- Removing g_spawn_check_exit_status() since its deprecated and using the recommended g_spawn_check_wait_status().
> Use AxParameter library from native SDK

- app/dockerdwrapper.c
Adding functionality that moves the contents of the data-root from the old location on the SD_Card to the new location as provided by the Axstorage setup. This is to support upgrading from  from previous releases of Docker* ACAP without losing data.
> Migrate data root

- app/dockerdwrapper.c
Defining string literals in a single place reduces the risk of spelling mistakes.
The functions for reading parameter values will never fail, so checking return values is pointless.
> Use constants for parameter names and remove trivial reader functions

- app/manifest.json
All current parameters are treated as bools so we might as well use the `bool` type
> Parameters as bool instead of enum

- app/postinstallscript.sh
Use the postinstall script to fail installation on devices that does not have container support.
- Fixes #65
> Fail installation on device without container support

- app/dockerdwrapper.c
- app/manifest.json
The default level (info) is the same as before.
Changing any of the log level parameters will restart dockerd.
Since the log levels are persisted as parameters,
is will be possible to debug start-up behavior,
by setting it to 'debug' before starting the application.
> Allow runtime changing of application and dockerd log level

- app/dockerdwrapper.c
- app/sd_disk_storage.h
Prevent SD card state change from restarting dockerd when SD card is not being used.
Also clarifying the comment about SD card unmounting.
> Ignore SD card state changes when not SD card is not used

- .github/workflows/cd.yml
As seen on docker-compose-acap the `--http1.1` flag is needed for the signing request when file sizes grow bigger.
> Workflow: add flag to curl command

- README.md
- app/dockerdwrapper.c
> Prevent dockerd from restarting after runtime error

- app/Makefile
- app/app_paths.h
- app/dockerdwrapper.c
- app/tls.c
- app/tls.h
> Log warnings instead of errors for missing TLS certs

- app/dockerdwrapper.c
HTTP requests are handled by another thread.
A successful file upload must allow dockerd to recover.
> Make dockerd 'allow start' flag thread safe

- .github/workflows/cd.yml
Add `runid` to cache key name to make sure we get a fresh cache when rebuilding for the same commit, e.g. when tagging for a release.
> Workflow: make cache key more unique

- README.md
- app/dockerdwrapper.c
- app/fcgi_server.c
- app/fcgi_server.h
- app/http_request.c
- app/http_request.h
Just as when changing a VAPIX parameter, completing a file upload over HTTP will restart dockerd.
> Restart dockerd after successful file upload

- README.md
- app/http_request.c
- app/tls.c
- app/tls.h
Check header and footer of TLS files being uploaded and reject if they don't match the file type.
> Reject upload of malformed TLS files

- app/dockerdwrapper.c
- app/http_request.c
- app/http_request.h
> Allow dockerd to recover when uploading a new file

- README.md
Do not refer to Docker Compose ACAP in the README this repo
> Removed typos with compose

- app/dockerdwrapper.c
start_dockerd() spanned several screens, so it could benefit from being split in two.
> Break out function for building daemon command line

- app/dockerdwrapper.c
There were some paths were status wasn't updated.
There were some paths were multiple errors were logged, but the first one contained enough information.
> Set status and log errors consistently

- app/dockerdwrapper.c
Clean up docker.pid file in /var/run/user instead of in the old rooted location of /var/run/docker.pid
> Clean up docker.pid file in /var/run/user

- app/dockerdwrapper.c
Even if the child process dies immediately after being launched, the call to g_child_watch_add() will register a callback that will alert the application of the exit code when the main loop is reached.
In this case, status will briefly change to STATUS_RUNNING before changing to DOCKERD_RUNTIME_ERROR.
> Remove unnecessary check that child process was started

- app/postinstallscript.sh
During a transition period, the postinstall script may run either as root or as the ACAP user, depending on global device settings. This needs to be taken into consideration when creating files from the postinstall script.
> Set ownership of empty daemon.json when running postinstall as root

- app/dockerdwrapper.c
The IPC socket should belong to group addon, so it can be accessed by other applications in the Docker Compose case.
> Set IPC socket group ownership to addon

- app/dockerdwrapper.c
With non-root user the migration will not be possible.
> Remove SD Card migration

- app/dockerdwrapper.c
Remove duplication of XDG runtime dir.
> Remove duplication of XDG runtime dir

- app/dockerdwrapper.c
- app/tls.c
- app/tls.h
Instead of keeping track of offset into and length of buffer, keep track of pointers to next input and to end of buffer. This means one less subtraction in every call to g_snprintf() and occationally statements that don't have to span several lines.
The --tlsverify flag was also moved from tls.c to the main file.
> Simplify concatenation of formatted strings

- app/dockerdwrapper.c
When resources are freed in the reverse order as they are allocated, it simplifies when you want to disable parts of the code when hunting for memory leaks and undefined behavior.
> Free resources in the reverse order of allocation

- app/dockerdwrapper.c
There is no need to unregister AXParameter callbacks. The hash table used for storing them will free its contents in ax_parameter_free().
> Remove unnecessary cleanup of AXParameter callbacks

- app/dockerdwrapper.c
* The ax_parameters[] array has been given a name reflecting its purpose.
* The array is now NULL-terminated, to simplify looping over it.
* The AXParameter callback function has been given a name reflecting its purpose.
* The unnecessary qualification of the parameter name when registering the callback has been removed.
> Clean up AXParameter callback registration code

- app/fcgi_server.c
- app/fcgi_server.h
- app/http_request.c
- app/http_request.h
By handling HTTP requests one-by-one rather than spawning a thread for each request, an attacker can no longer force the app to create multiple threads. It also leads to simpler code and fixes the failure to free the memory allocated for the request.
> Handle HTTP requests one-by-one

- app/manifest.json
Reduce the default log level of dockerd to `warn`
> Set dockerd default log-level to warning

- app/dockerdwrapper.c
It takes a few moments for the SD card to become available, so if the SD card setting is enabled, this log message will show up every time the application starts.
> Log missing SD card as a warning rather than an error

- app/dockerdwrapper.c
TLS is enabled by default and uploading certificates over HTTP needs to happen after the application has started, so the user cannot avoid this message when using HTTP rather than SSH.
The warning message already exists in tls_log_missing_cert_certs(), so this change only removes the generic error message at the call site.
> Log missing TLS certificates as a warning rather than an error

- app/dockerdwrapper.c
If AXParameter or environment variable setup fails, a detailed message is already logged in the failing function. There is no need to repeat that message with less detail at the call site.
> Remove repetitive log messages

- README.md
- app/postinstallscript.sh
When 'Allow root-privileged apps' is turned on,
the post-install script will run as root,
so it has the ability to change the ownership of the files on the SD card
> Try to change ownership of files on SD card during installation

- Dockerfile
- README.md
- app/Makefile
- build.sh
If enabled, the code will contain instrumentation that checks for various errors, reports them on stdout and results in a non-zero exit code.
> Add option for building with sanitizers

- app/postinstallscript.sh
* Use variables to reduce code duplication.
* Use variables to increase readability.
* Break comment line that exceeded 100 characters.
> Clean up post-install script

- .github/actions/docker-build-action/action.yml
Old env variable `DOCKER_BUILD_NO_SUMMARY` is deprecated
> Set DOCKER_BUILD_SUMMARY to false

- app/dockerdwrapper.c
If SD card has been selected for storage, delay the start of dockerd a few seconds.
> Delay start of dockerd until SD card is available

- app/dockerdwrapper.c
The buffer holding the message "Starting dockerd with..." is currently too short and the final part, "as storage", will be truncated for certain combinations of settings.
> Avoid truncation of startup message

- app/dockerdwrapper.c
Docker daemon (dockerd) typically sends a SIGTERM signal after 10 seconds. Previously, we waited 20 seconds before sending a SIGKILL, but systemd would sometimes reach its timeout and forcefully terminate the process before then approximately at 14-15 seconds. To prevent this issue I havve decreased the wait time to 13 seconds before sending SIGKILL.  SIGTERM sometimes stops the process gracefully but it’s not always reliable so making this change is necessary.
> Decrease the wait time before SIGKILL
