Dockerfile.acap, app/postinstallscript.sh
dockerd needs a ps command that is able to handle -a, - e, and  -o uid=PID flags. The busybox version of the command, available in the camera, handles no flags.
https://github.com/moby/moby/blob/2b70006e3bfa492b8641ff443493983d832955f4/daemon/top_unix_test.go
=> Adding a more capable ps command

.github/workflows/build-dockerfile.yml, Dockerfile.acap, Dockerfile.dockerd
Step acap-native-sdk to first official release version 1.0.
Reference: ECODEVT-171
Added build test of Dockerfiles
=> Make Dockerfiles more consistent with argument usage

app/manifest.json
=> Step version to 1.2.1

app/manifest.json
Change-Id: I78fb22a1f4440d45914c806347716a071670502d
=> step version to 1.2.2

README.md
Update compatibility instructions with a command to enable SSH before using it to verify container support.
- Fixes #55
=> docs(readme): update ssh instructions

.github/workflows/build-dockerfile.yml, .github/workflows/markdownlint.yml, .github/workflows/shellcheck.yml
Let's upgrade to the newest version of [actions/checkout](https://github.com/actions/checkout).
=> Upgrade GitHub Action 'actions/checkout'

.github/workflows/build-dockerfile.yml
Minor changes to style in one of the GitHub Actions workflows.
=> Update style to match other GitHub Actions workflows

.github/workflows/markdownlint.yml, .github/workflows/shellcheck.yml
Remove unnecessary configuration.
=> Refactor GitHub Actions triggers

README.md
Added instruction on how to configure Docker to automatically use your client certificate when connecting to the Axis device.
=> Improve TLS Setup chapter

app/LICENSE
License from https://github.com/moby/moby/blob/master/LICENSE
=> Add dockerd license to ACAP application

.github/workflows/build-dockerfile.yml, .github/workflows/markdownlint.yml, .github/workflows/shellcheck.yml, Dockerfile.acap, Dockerfile.dockerd, README.md, app/Makefile, build.sh
Updated docker parts of repo to use heredocs and buildx. Documentation updated to inform of buildx use.
Also updated workflows to run on pull-requests and renamed for clarity.
=> Use buildx and heredocs

.github/actions/metadata-action/action.yml, .github/dependabot.yml, .github/workflows/cd.yml
Added Dependabot version monitoring
=> Added Dependabot version monitoring

.github/workflows/cd.yml, hooks/build
=> Remove build docker hub

.clang-format, .gitignore, app/dockerdwrapper.c
Apply clang-format to dockerdwrapper.c and add a .clang-format file in the repo.
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have verified that my code follows the style already available in the repository
- [x ] I have made corresponding changes to the documentation
=> Apply clang-format to dockerdwrapper.c

.vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md, README.md
Updated README and added some helper files.
=> Documentation for rootless preview

app/dockerdwrapper.c, app/postinstallscript.sh
ACAPSDK - 1536
https://jira.se.axis.com/browse/ACAPSDK-1536
- [ x ] I have performed a self-review of my own code
- [ x ] I have verified that the code builds perfectly fine on my local system
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have verified that my code follows the style already available in the repository
=> Set required environment variables for rootless docker ACAP

build.sh
Allow building with cache and with a simpler progress bar.
=> Add command line options to build.sh

app/dockerdwrapper.c
Refactoring code for readout and handling of parameter status.
=> refactor handling of parameter settings

app/postinstallscript.sh
Requiring containerd.service should not be needed so we remove it
=> remove containerd requirement

app/dockerdwrapper.c
Create dockerd folder on the SD card before checking the folder.
=> Check filesystem on subfolder instead of top folder

app/dockerdwrapper.c
The default value of /var/run/dockerd, on a tmpfs, is a much better place for the execution state,
that on a flash drive.
=> Remove creation of unused exec_root directory

app/dockerdwrapper.c
This reverts commit 774fbf62d726741ad33907c352ac70559b01b358.
=> Revert "Pass around data root in settings struct (#147)"

Dockerfile
Bump Docker Engine to [26.0.0](https://docs.docker.com/engine/release-notes/26.0/#2600)
=> bump up to docker engine 26.0.0

app/manifest.json
Update version to 1.5.0 in preparation for release
=> update version in preparation for release

.github/workflows/send-dispatch.yml
A workflow action that creates a `workflow_dispatch` event in docker-compose-acap when a PR is merged to main
=> Add action to send workflow dispatch

app/dockerdwrapper.c
=> Allow multiple headers in certs

app/Makefile, app/dockerdwrapper.c
=> Introduce constants for application name and directories

README.md, app/Makefile, app/dockerdwrapper.c, app/log.c, app/log.h, app/sd_disk_storage.c
=> Allow log be directed to stdout instead of syslog

.editorconfig, app/manifest.json, build.sh
=> Use 4 spaces indentation in manifest.json

app/dockerdwrapper.c
When there are multiple AXParameter callbacks in a queue, such as during the first parameter change after installation, any parameter usage, even outside a callback, will cause a 20 second deadlock per queued callback.
The workaround is to delay the call back to g_main_loop_quit() by 1 second using a timer callback.
=> Prevent deadlock when acting on parameter changes

app/dockerdwrapper.c
- Added macros for calls to `g_main_loop` - functions to add debug log messages 
- Added debug log of `dockerd` command 
- Added debug log when parameter_changed_callback is called
=> Debug log for main loop and dockerd command

app/dockerdwrapper.c
=> Avoid crash due to free() before malloc()

README.md, app/dockerdwrapper.c, app/manifest.json
Added a status parameter that can be read via param.cgi. It signals the current state of the application, i.e. is it running, is dockerd running or what prevents dockerd from running.
=> Added status parameter to declare state of application

app/dockerdwrapper.c
By logging the PID, it's easier to tell sessions apart.
The log level has been reduced to log_debug,
since there are log_info messages that better convey the state transitions in the applications.
Exit code and signal number are no longer mixed up in the log. The new log messages look like this:
* killall -SIGINT  dockerd → "exited with exit code 0"
* killall -SIGTERM dockerd → "exited with exit code 0"
* killall -SIGABRT dockerd → "exited with exit code 2"
* killall -SIGKILL dockerd → "was killed by signal 9"
=> Log more details around child process start and stop

app/dockerdwrapper.c
Valgrind reports memory leaks from ax_parameter_new(), so instead of calling it on the fly, it will now be called only once and then passed around inside app_state struct.
=> Initialize AXParameter only once to prevent memory leak

app/dockerdwrapper.c
Stop dockerd by sending SIGTERM and if it fails to terminate, send SIGKILL after 20 seconds.
When all containers stop quickly, dockerd will stop in just 1 second. If one or more containers refuse to stop, dockerd will send SIGKILL after 10 seconds, meaning dockerd will take 11 or 12 seconds to stop.
The old behavior was to always wait 10 seconds, then send SIGTERM, but the intention was the behavior described above, save for a too short SIGKILL delay.
=> Stop dockerd nicely

.github/actions/docker-build-action/action.yml, .github/actions/update-acap-manifest-action/action.yml, .github/dependabot.yml, .github/workflows/cd.yml, .github/workflows/send-dispatch.yml
Refactors the cd workflow to add sha to filenames and to only sign when merging to main
=> Refactor workflow and actions

.github/workflows/cd.yml
- Fix env-vars for pre-release job
- Be more selective on when to run a step or job
=> Fix pre-release job of workflow

README.md, app/manifest.json
Setting base version to 2.0 due to breaking changes.
=> Update version to 2.0 for coming release

.github/workflows/cd.yml
Pick up the correct variables for uploading to a pre-release
=> Pick up the correct variables

README.md, app/dockerdwrapper.c
- Added a status code for failing data root migration
- Set correct status when SD Card is missing
- Update README.md 
- Fixes Status parameter being wrong
=> Fix setting Status parameter value

app/dockerdwrapper.c
=> Make final status change while AXParameter is available

app/dockerdwrapper.c, app/log.c, app/log.h
=> Allow debug logging from multiple threads

.github/workflows/cd.yml, .gitignore, Dockerfile, README.md, build.sh
Refactor dockerfile and rename ACAPARCH to ARCH to be consistent with other projects
=> Refactoring Dockerfile

README.md, app/Makefile, app/dockerdwrapper.c, app/fcgi_server.c, app/fcgi_server.h, app/fcgi_write_file_from_stream.c, app/fcgi_write_file_from_stream.h, app/html/index.html, app/http_request.c, app/http_request.h, app/manifest.json
=> Upload and delete certificates using HTTP requests

README.md
=> Review so far

app/dockerdwrapper.c
Adds additional environment variables needed to run rootles Docker
=> Add env variables for rootless

app/app_paths.h, app/dockerdwrapper.c
Create the rootlesskit command.
=> Create rootlesskit command

app/dockerdwrapper.c
The PID returned from g_spawn_async() is that of rootlesskit, not dockerd, so it makes sense to talk about the rootlesskit process in the log_debug() statements.
Also changed so 0 rather than -1 means no child process is running.
=> Use rootlesskit instead of dockerd where relevant

app/dockerdwrapper.c
=> Log exit code

Dockerfile
Base docker_binaries stage on sdk_image instead of build_image
=> Dockerfile stage change

app/dockerdwrapper.c
Move callback function to a place where no forward declaration is necessary and give it a name explaining what it does rather than when it is called.
No changes to any of the function bodies.
=> Move and rename process exit callback

README.md, app/manifest.json
Add `sdk` as secondary group. Needed to run parameter example
=> Add sdk group

app/dockerdwrapper.c
Fix memory leak during child process exit code checking
=> Fix memory leak during child process exit code checking

README.md
Release  table points to release candidate instead of latest release.
=> Don't refer to a release until it is done

README.md
=> Update links for release

README.md
=> Set correct dockerd version in table

README.md
Adding guidance to enable 'Allow unsigned apps' toggle before installing an app.
=> Add instruction to enable the Allow unsigned toggle

app/LICENSE
Include the GPL license text in the third party license section
=> Include license text for nsenter, ps and slirp4netns

app/dockerdwrapper.c
=> Use g_unix_signal_add instead of sigaction

README.md
=> Fix lint issue in README

app/app_paths.h, app/dockerdwrapper.c
Set env variable for XTABLES_LOCKFILE to /tmp to avoid failing on permission issue
=> Use fake lock-file
